Algoritmo "sequencia"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/03/2024
Var
numeros : vetor[1..10] de inteiro
listaNum : vetor[1..10] de inteiro
contador : inteiro

Inicio
contador <- 1
para contador <- 1 ate 10 faca
  escreva("digite os numeros: ")
fimpara
Fimalgoritmo